"""add_created_at_to_projects

Revision ID: eac3059398fb
Revises: 0002
Create Date: 2026-05-01 05:54:14.156450
"""
from alembic import op
import sqlalchemy as sa


revision = 'eac3059398fb'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_invites', 'token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('projects', sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'created_at')
    op.alter_column('project_invites', 'token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
